source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.0'
use_frameworks!

target 'BXPhotoViewer_Example', :exclusive => true do
  pod "BXPhotoViewer", :path => "../"
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end

target 'BXPhotoViewer_Tests', :exclusive => true do
  pod "BXPhotoViewer", :path => "../"

  
end
