source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXPhotoViewer_Example', :exclusive => true do
  pod "BXPhotoViewer", :path => "../"
end

target 'BXPhotoViewer_Tests', :exclusive => true do
  pod "BXPhotoViewer", :path => "../"

  
end
